wandb_version: 1

GYM environment:
  desc: null
  value: CartPole-v1
NEAT config/Connection addition rate:
  desc: null
  value: 0.5
NEAT config/Connection change rate:
  desc: null
  value: 0.9
NEAT config/Fitness Threshold:
  desc: null
  value: 1000.0
NEAT config/Generations:
  desc: null
  value: 30
NEAT config/Inputs:
  desc: null
  value: 10
NEAT config/Max-Species:
  desc: null
  value: 3.0
NEAT config/Mutation Rate:
  desc: null
  value: 0.8
NEAT config/Node Mutation rate:
  desc: null
  value: 0.03
NEAT config/Outputs:
  desc: null
  value: 1
NEAT config/Population:
  desc: null
  value: 50
NEAT config/Re-enable rate:
  desc: null
  value: 0.25
NEAT config/Saved population:
  desc: null
  value: 0.8
Name:
  desc: null
  value: V1
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
    start_time: 1674590975.228845
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.1
      5: 0.13.7
      8:
      - 3
      - 5
